### ISSUE TITLE
Exception in thread "XPCOMMessageLoop" java.lang.UnsatisfiedLinkErro

### ISSUE THREAD

**Issue by cdhagmann** [spm/spm-docker#6]
When running
```
docker run spmcentral/spm:latest fmri
```
it returns 
```
 ___  ____  __  __                                            
/ __)(  _ \(  \/  )                                           
\__ \ )___/ )    (   Statistical Parametric Mapping           
(___/(__)  (_/\/\_)  SPM12 - https://www.fil.ion.ucl.ac.uk/spm/


SPM12: v7487                                       21:00:48 - 10/12/2019
========================================================================
Initialising SPM                        :                   ......Exception in thread "XPCOMMessageLoop" java.lang.UnsatisfiedLinkError: /opt/mcr/v95/sys/jxbrowser/glnxa64/xulrunner/xulrunner-linux-64/libsqlite3.so: libasound.so.2: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.teamdev.jxbrowser.gecko.xpcom.impl.linux.LinuxMozillaToolkit.c(Unknown Source)
	at com.teamdev.jxbrowser.gecko.xpcom.impl.linux.LinuxMozillaToolkit.a(Unknown Source)
	at com.teamdev.jxbrowser.gecko.xpcom.MozillaToolkit.initialize(Unknown Source)
	at com.teamdev.jxbrowser.gecko.xpcom.AppShellXPCOMThread$b.run(Unknown Source)
Exception in thread "XPCOMMessageLoop" java.lang.UnsatisfiedLinkError: /opt/mcr/v95/sys/jxbrowser/glnxa64/xulrunner/xulrunner-linux-64/libsqlite3.so: libasound.so.2: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.teamdev.jxbrowser.gecko.xpcom.impl.linux.LinuxMozillaToolkit.c(Unknown Source)
	at com.teamdev.jxbrowser.gecko.xpcom.impl.linux.LinuxMozillaToolkit.a(Unknown Source)
	at com.teamdev.jxbrowser.gecko.xpcom.MozillaToolkit.initialize(Unknown Source)
	at com.teamdev.jxbrowser.gecko.xpcom.AppShellXPCOMThread$b.run(Unknown Source)
Exception in thread "XPCOMMessageLoop" java.lang.UnsatisfiedLinkError: /opt/mcr/v95/sys/jxbrowser/glnxa64/xulrunner/xulrunner-linux-64/libsqlite3.so: libasound.so.2: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.teamdev.jxbrowser.gecko.xpcom.impl.linux.LinuxMozillaToolkit.c(Unknown Source)
	at com.teamdev.jxbrowser.gecko.xpcom.impl.linux.LinuxMozillaToolkit.a(Unknown Source)
	at com.teamdev.jxbrowser.gecko.xpcom.MozillaToolkit.initialize(Unknown Source)
	at com.teamdev.jxbrowser.gecko.xpcom.AppShellXPCOMThread$b.run(Unknown Source)
Exception in thread "XPCOMMessageLoop" java.lang.UnsatisfiedLinkError: /opt/mcr/v95/sys/jxbrowser/glnxa64/xulrunner/xulrunner-linux-64/libsqlite3.so: libasound.so.2: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.teamdev.jxbrowser.gecko.xpcom.impl.linux.LinuxMozillaToolkit.c(Unknown Source)
	at com.teamdev.jxbrowser.gecko.xpcom.impl.linux.LinuxMozillaToolkit.a(Unknown Source)
	at com.teamdev.jxbrowser.gecko.xpcom.MozillaToolkit.initialize(Unknown Source)
	at com.teamdev.jxbrowser.gecko.xpcom.AppShellXPCOMThread$b.run(Unknown Source)
Exception in thread "XPCOMMessageLoop" java.lang.UnsatisfiedLinkError: /opt/mcr/v95/sys/jxbrowser/glnxa64/xulrunner/xulrunner-linux-64/libsqlite3.so: libasound.so.2: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.teamdev.jxbrowser.gecko.xpcom.impl.linux.LinuxMozillaToolkit.c(Unknown Source)
	at com.teamdev.jxbrowser.gecko.xpcom.impl.linux.LinuxMozillaToolkit.a(Unknown Source)
	at com.teamdev.jxbrowser.gecko.xpcom.MozillaToolkit.initialize(Unknown Source)
	at com.teamdev.jxbrowser.gecko.xpcom.AppShellXPCOMThread$b.run(Unknown Source)
..done

SPM present working directory:
	/
```

It seems that some dependencies are not correctly map in the docker image.

**Comment by gllmflndn** [comment]
Hi @cdhagmann,

Yes, I'm aware of this happening when you are trying to launch the GUI (I was expecting the container to be mainly used from the command line). I didn't succeed to solve this by trying to add potentially missing packages so I instead removed the call that generates these error messages (it's for something totally unimportant).

Part of the fix is there: https://github.com/spm/spm-docker/blob/master/matlab/Dockerfile#L29
and it also requires a change in SPM by adding the following piece of code in https://github.com/spm/spm12/blob/r7487/spm_browser.m#L53
```
if strcmp(getenv('SPM_HTML_BROWSER'),'0')
  error('HTML browser disabled.');
end
```
This requires a recompilation of the SPM12 Standalone - there will be a new version with the next update that should take place soon. I can give you access to a beta version if you cannot wait (you will have to build the Docker container yourself) but, otherwise, it seems that SPM still runs despite the error messages so they can be ignored:
```
xhost local:root
docker run -e DISPLAY=$DISPLAY -v /tmp:/tmp -v /tmp/.X11-unix:/tmp/.X11-unix spmcentral/spm:latest fmri
```

**Comment by cdhagmann** [comment]
Thanks for the quick reply. I can wait for the official release, but wouldn't mind access to the beta. I am just getting started using SPM to convert an existing Matlab script to standalone and wasn't sure if the error was breaking or not. Do you know of any resources for using SPM Standalone? Thanks you for this docker image.
